### ISSUE TITLE
Installation link broke

### ISSUE THREAD

**Issue by ItN0wPompelup** [pascal71/community.tplink#2]
Hello, I apologize in advance if this message has nothing to do here I am new to github/ansible.
I don't know if I'm the only one affected but it's impossible for me to install the collection via "ansible-galaxy collection install community.tplink". Am I the only one in this situation?
Thanks,

Pompélup

**Comment by pascal71** [comment]
Quoting ItN0wPompelup ***@***.***>:

> Hello, I apologize in advance if this message has nothing to do here  
> I am new to github/ansible.
> I don't know if I'm the only one affected but it's impossible for me  
> to install the collection via "ansible-galaxy collection install  
> community.tplink". Am I the only one in this situation?
> Thanks,
>
> Pompélup

Good morning,

It might be that (the repo has collected some age) the link indeed  
doesn't work well nowadays. Manual install is possible. But as I did  
see more people picking up interest on te repo recently, I will pick  
this one up next week and also update it for the newer TP-Link models.

Kind regards,

    Pascal van Dam

**Comment by ItN0wPompelup** [comment]
Okay, good news. I will try the manual installation. 
Thank for your work

Pompelup
